### ISSUE TITLE
Read Color of Text 

### ISSUE THREAD

**Issue by hrodriguez-** [grevit-dev/DynamoPDF#2]
@moethu reading the color of text will help us identify if the notes on the PDF are either "notes to the drafter or notes that need to be incorporated in to the sheet. For the most part a company will have standards for how to mark up the pdf. 

![image](https://cloud.githubusercontent.com/assets/7632885/22339188/bb237b94-e3ae-11e6-929c-0dd871f73559.png)

**Comment by moethu** [comment]
implemented
