### ISSUE TITLE
Get Subject - Element 

### ISSUE THREAD

**Issue by hrodriguez-** [grevit-dev/DynamoPDF#3]
@moethu i was looking closer at the Markup thing and found that if you can pull the "Subject" as an attribute this could lead to a good way to sort out elements when they come to Revit. Each of the structural elements will be tag with a specific type see image 2. 

![image](https://cloud.githubusercontent.com/assets/7632885/22349177/33467110-e3d4-11e6-8417-3ca4cd1cd6f6.png)

Attribute 
![image](https://cloud.githubusercontent.com/assets/7632885/22349210/5b188606-e3d4-11e6-9106-81a128baf87a.png)

**Comment by moethu** [comment]
@hrodriguez- please see the latest version (1.2) it now allows you to read the properties you requested and it contains nodes to write pdfs as well
