### ISSUE TITLE
Multi - Line text

### ISSUE THREAD

**Issue by splash6** [grevit-dev/DynamoPDF#4]
Multi line text doesn't seem to be working well for me because the text on each line overlaps with the following lines.

**Comment by moethu** [comment]
right so the line spacing is not setup correctly, I will check

**Comment by moethu** [comment]
@splash6 did you try the leading input of the phrase node? according to itextsharp this should be the line spacing: https://github.com/grevit-dev/DynamoPDF/blob/22226e7c12143f61874cb2897e1c1fe5a424dede/DynamoPDF/Content/Phrase.cs#L18-L31

**Comment by moethu** [comment]
![image](https://user-images.githubusercontent.com/8201465/34096809-047a6b08-e3d7-11e7-82ec-07d21bd0a6e9.png)

**Comment by moethu** [comment]
will close this for now
