### ISSUE TITLE
Add Image to PDF

### ISSUE THREAD

**Issue by mdengusiak** [grevit-dev/DynamoPDF#5]
I am trying to add Image to PDF but something does not work?

![image](https://user-images.githubusercontent.com/14005893/27590675-5a5c93a2-5b47-11e7-903b-e5394c6d5ba8.png)

**Comment by hrodriguez-** [comment]
@mdengusiak 

W.AddAnnotationtoPDF takes Annotation.Annotation as the input.

This workflow will create an image on a pdf (possible merge after you export all images to that pdf)

![image](https://user-images.githubusercontent.com/7632885/27597892-5ce85854-5b29-11e7-8a6a-60d2cb9946dd.png)

i am getting a different error on the Write.AddAnnotation - my error is regarding permission to write on the folder. see if you can write to your local folder. 

![image](https://user-images.githubusercontent.com/7632885/27597957-9d646fd0-5b29-11e7-85b6-0012198bee72.png)

**Comment by mdengusiak** [comment]
Hi 
it worked when generating new file

![image](https://user-images.githubusercontent.com/14005893/27599766-b2dd0ccc-5b61-11e7-8b1d-c09704c01288.png)

but can not get it working just add image to existing file...?    

![image](https://user-images.githubusercontent.com/14005893/27599901-21a4436e-5b62-11e7-8165-e6843c9c7aa0.png)

**Comment by moethu** [comment]
@mdengusiak you are using AddAnnotationsToPDF, and Image is not an annotation. Annotations are only the red markups for PDFs, like this:
![image](https://user-images.githubusercontent.com/8201465/33655336-0cb1b83e-da73-11e7-93e0-4bf745d1d1aa.png)
Appending Content is currently not supported in this library, do you still need this?
